runtime: python27
api_version: 1
threadsafe: true
service: default

handlers:
- url: /admin/static
  static_dir: dist/static
  login: admin
  secure: always
  redirect_http_response_code: 301
  http_headers:
    X-Frame-Options: "DENY"
    Strict-Transport-Security: "max-age=2592000; includeSubdomains"
    X-Content-Type-Options: "nosniff"
    X-XSS-Protection: "1; mode=block"

- url: /admin.*
  login: admin
  mime_type: text/html
  static_files: dist/index.html
  upload: dist/index.html
  secure: always
  redirect_http_response_code: 301

# Delete Me
- url: /.*
  mime_type: text/html
  static_files: home.html
  upload: home.html
  secure: always
  redirect_http_response_code: 301

skip_files:
#File Types
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*\.soy
- ^(.*/)?.*\.log
- ^(.*/)?\.DS_Store

# App Directory
- ^(.*/)?.*\.sh
- .*package.json
- .*node_modules(/.*)?
