runtime: python27
api_version: 1
threadsafe: true
service: api

handlers:
- url: .*/task/.*
  login: admin
  script: routes.TASKS
  secure: always

- url: .*
  script: routes.APPLICATION
  secure: always

libraries:
- name: pycrypto
  version: 2.6
- name: ssl
  version: 2.7.11

skip_files:
#File Types
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*\.soy
- ^(.*/)?.*\.log
- ^(.*/)?\.DS_Store
- ^(.*/)?\.coveragerc
- ^(.*/)?\.datastore
- .*README.md
- .*Makefile
- .*package.json

# App Directory
- ^(.*/)?.*\.sh
- .*node_modules
- .*gae_storage
- .*tests


#Specific Files
- ^(.*/)?.*(?<!robots)\.txt  # exclude all except robots.txt
