runtime: python27
api_version: 1
threadsafe: true
service: api

handlers:
- url: .*/task/.*
  login: admin
  script: routes.TASKS
  secure: always

- url: .*
  script: routes.APPLICATION
  secure: always

libraries:
- name: pycrypto
  version: 2.6
- name: ssl
  version: 2.7.11

skip_files:
#File Types
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*\.soy
- ^(.*/)?.*\.log
- ^(.*/)?\.DS_Store
- ^(.*/)?\.coveragerc
- ^(.*/)?\.datastore

# App Directory
- ^(.*/)?.*\.sh
- .*package.json
- .*node_modules(/.*)?

skip_files:
#File Types
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*\.scss
- ^(.*/)?.*\.soy
- ^(.*/)?.*\.log
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?\.DS_Store
- ^(.*/)?\.coveragerc
- ^(.*/)?\.datastore

#Root Directory
- README.md
- Makefile

#Children Directory
- .*tests/.*
- .*egg-info/.*
- .*dist-info/.*
- ^static/js/common/closure-library.*

#Specific Files
- ^(.*/)?.*(?<!robots)\.txt  # exclude all except robots.txt
